### ISSUE TITLE
js error

### ISSUE THREAD

**Issue by anna-nz** [kavanmevada/flex_masonry_pure_js#2]
Looks like a very cool plugin but it doesn't work for me. 

Gives me this error:

**TypeError: Cannot read property 'classList' of null
    at flex_masonry (flex_masonry.self-cec4d8df87ca8eb8585b83143619d69bfd06631d68e6968e14a2202cfb93a460.js?body=1:77):**
 element.classList.add('sm-loaded');

**Comment by kavan-mevada** [comment]
Check out this demo: https://codepen.io/kavanmevada/pen/JRwRkK

**Comment by anna-nz** [comment]
Thanks for your fast reply!!!

Seems like same issue:
<img width="427" alt="Screen Shot 2019-06-26 at 8 37 36 AM" src="https://user-images.githubusercontent.com/31054990/60131520-abfc6900-97ed-11e9-95a1-63500b16cd6d.png">

**Comment by anna-nz** [comment]
wrapped into document.addEventListener("DOMContentLoaded", function() {    ...   }) and it worked!
